### ISSUE TITLE
Table: Visualize Categorical data in matrix (no color)

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#10]
Let's visualize categorical data like this: 

![img_20170209_133656](https://cloud.githubusercontent.com/assets/2039375/22802212/2f0fc98a-eecd-11e6-82eb-0740629ff334.jpg)

I.e., when we have categories of one class, we still show a whole column for each category (e.g., male and female get their own column). Between categories of different classes, we increase the spacing (as in between female and suicide).

**Comment by ngehlenborg** [comment]
@alexsb: Can you clarify what the rationale is? I see advantages (no reuse of colors for different categories), but also disadvantages (width of matrix grows rapidly even for single categorical variables, aggregation is harder to handle).

**Comment by alexsb** [comment]
First, I'm not saying that we don't want to ever try the color-code categories approach, but I'd start with this implementation. 

Generally, I'm a fan of using position for encoding data. This does that. It's costing a bit of space, but that might be worth it. I'd like to see it first with our data and if scalability is a significant concern we will revisit it. 

For aggregation - the opposite is true. We can use these little squares as bar charts that show how many are male or female, for example. 

I think that lots of colors will get very confusing, and finding the place to label it isn't easy either. Let's say you have 5-6 categories - where would you show the labels? I'd probably use a dedicated space for labeling a selected group of categories, but that means that you have to interact to read everything.
