### ISSUE TITLE
Mark and on-demand connect duplicated Nodes

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#111]
We duplicate nodes to remove cycles from the tree. Now we also need to indicate that the nodes are duplicated. 

We will use little arrows pointing to each other:

![image](https://cloud.githubusercontent.com/assets/2039375/24176032/59ae7fa4-0e5f-11e7-8fc3-f216280795d6.png)

On demand, we'll add an edge connecting the duplicates.

**Comment by cnobre** [comment]
done but could use a few positioning adjustments. will include that in an 'aesthetics improvements' issue I'm creating.
