### ISSUE TITLE
Children of multi-parent families not displayed correctly in kidgrid

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#117]
See this case: 

![image](https://cloud.githubusercontent.com/assets/2039375/24370743/c10521fa-12e5-11e7-8584-f7b8bb2a9a86.png)

There is only one male in the kidgrid, in addition to the suicide case. There should be two.

**Comment by cnobre** [comment]
yeah, I noticed that last night. It’s because they have different dads. and the kid grid offsets cycles through all the kids in a given parent's  .children array and offsets them appropriately.  So the two males are placed over each other in that example. will add handling for this case.
