### ISSUE TITLE
Hide years when there is not enough space

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#13]
![image](https://cloud.githubusercontent.com/assets/2039375/22802967/25c985b6-eed0-11e6-96a9-1a3e3cafb0b9.png)

What we probably want to see is the first and the last year in this aggregated space.

**Comment by cnobre** [comment]
![screen shot 2017-02-09 at 6 25 39 pm](https://cloud.githubusercontent.com/assets/4120607/22810326/4c54379c-eef5-11e6-8cb1-d82d9c1c30f1.png)


![screen shot 2017-02-09 at 6 25 59 pm](https://cloud.githubusercontent.com/assets/4120607/22810332/564c680a-eef5-11e6-9c60-1bf5c5a67de3.png)
