### ISSUE TITLE
Consistently use :hover pseudo-class for anything that can be hovered and clicked.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#142]
See 

https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

This will change the cursor from an arrow to a hand. 

We do have that in the jquery data selection panel already, but the D3 things are missing it.

**Comment by cnobre** [comment]
I've been using cursor:pointer to set the pointer to a hand. Is this better than that?

**Comment by alexsb** [comment]
No idea.

**Comment by alexsb** [comment]
I think this is largely implemented. Will add new issues if missing somewhere.

**Comment by cnobre** [comment]
ok
