### ISSUE TITLE
Allow to select primary mapping attributes in data selection panel

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#17]
From the list of attributes, we want to be able to select 

 * one primary attribute that drives the coloring of the nodes. In our common example this is "committed suicide"
 * one secondary attribute that is displayed to the right of the node. Currently, this is the "life line", i.e., the life span of the people.

Both can be either categorical or numerical or an item measured multiple times over a person's life. 

These could be realized using a dedicated button associated with each entry:

![img_20170209_173847](https://cloud.githubusercontent.com/assets/2039375/22809342/ee16e216-eeee-11e6-82f6-2647a2a3dcea.jpg)

When an item is selected to be the primary or the secondary attribute, the button will be highlighted and will always  be visible. Otherwise, these buttons are only visible on hover (this isn't correctly shown in the sketch). 

Gender is explicitly excluded, since this is encoded in the shape.

**Comment by cnobre** [comment]
done
