### ISSUE TITLE
allow hover event to propagate through cells to background row

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#174]

**Comment by alexsb** [comment]
Right now, you have to hover over the background of a row, if you hover over a visualization, it doesn't highlight.

**Comment by alexsb** [comment]
Btw, propagate through is one approach to this, the other would be to trigger the highlight also on all the svg elements that are rendered in the row. I don't know whether propagate through is actually possible?

**Comment by cnobre** [comment]
done
