### ISSUE TITLE
fix decyling bug where duplicates are generated unenecessarily

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#178]

**Comment by alexsb** [comment]
Example: Family 1474: 

![image](https://user-images.githubusercontent.com/2039375/32795640-8f67085c-c929-11e7-9a5e-5f24ca5be718.png)

**Comment by alexsb** [comment]
Also: 

![image](https://user-images.githubusercontent.com/2039375/33243715-8175e30c-d2a8-11e7-9574-af6efae8c444.png)

Family 27251 in anon dataset. Why is this person duplicated?

**Comment by cnobre** [comment]
![screen shot 2017-11-28 at 10 50 54 am](https://user-images.githubusercontent.com/4120607/33342207-8863d7ae-d43e-11e7-99ab-6c0f6c41ac80.png)

(first example, now fixed)

![screen shot 2017-11-28 at 1 12 56 pm](https://user-images.githubusercontent.com/4120607/33342217-8fc0ce3a-d43e-11e7-8ca4-534c09e458d1.png)
(second example, now fixed)
