### ISSUE TITLE
Handle cases where individuals appear in multiple families.

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#179]
We should create a 'lineageID' that is the combination of familyID and relativeID. 

This will disambiguate the same person in two families. Might fix some layout bugs.

**Comment by alexsb** [comment]
This is very likely to be the cause of many problems.

Families 4782 and 4784 are almost identical, except for a founder. If I show them individually, they are fine. If I show both, this happens: 

![image](https://user-images.githubusercontent.com/2039375/32795344-9d6dd670-c928-11e7-9633-3351af9ad035.png)

**Comment by cnobre** [comment]
you are right. even the labels are overlapping

**Comment by alexsb** [comment]
Works
