### ISSUE TITLE
Visualize flexibly mapped primary attribute in graph.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#18]
As discussed in #17, we want to be able to select a primary and a secondary attribute for direct mapping in the graph. 

The primary mapping will determine the node color. For categorical values, we will choose a qualitative color scale (black/white for binary categories, [this colorbrewer scale](http://colorbrewer2.org/?type=qualitative&scheme=Paired&n=8) for multiple categories) and visualize a legend of the color scale at the bottom of the graph. 

For continuous color values, we will use a quantitative color brewer scale, appropriately treating quantitative continuous and diverging scales. Again, we will visualize a legend at the bottom of the graph. 

Two components: 
 * [x] One-node mapping works.
 * [ ] Legends implemented.

**Comment by cnobre** [comment]
<img width="1024" alt="primary_attribute" src="https://cloud.githubusercontent.com/assets/4120607/22850557/a3bef1c4-efc8-11e6-9f43-e0416fa3c935.png">


<img width="1024" alt="secondary_attribute" src="https://cloud.githubusercontent.com/assets/4120607/22850559/a750bb24-efc8-11e6-9341-c3ac0ba36b93.png">

**Comment by alexsb** [comment]
We decided to use the node to always encode a binary value (primary phenotype yes/no). When the primary phenotype is binary, this is all that is to do. 

In cases where the binary value is derived from a continuous or categorical value, we will use a bar to the left of the node. For categorical values, this will be a color. For numerical values, this will be a bar with a height proportional to the value.

**Comment by alexsb** [comment]
Works!
