### ISSUE TITLE
add back ability to set primary attributes 

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#180]
potentially with menu icon under each col header

**Comment by cnobre** [comment]
POI works for most cases. Not for some (like gender).

**Comment by alexsb** [comment]
A major open issue are also numerical values. 

Also, labels/strings/ids can't be set as POIs or as Starred at the moment. That should be possible, all elements that have a value should be POI/starred.

**Comment by cnobre** [comment]
actually labels/strings/ids can be starred and set as POI (if there is a value, it evaluates to true). 

As far as numerical values, you can set them as POI, you just can't change the default range yet.

**Comment by cnobre** [comment]
modified to only address primary attributes. POI has been re-instated
