### ISSUE TITLE
Layout Issue Family 212

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#186]
![image](https://user-images.githubusercontent.com/2039375/32795544-3c86ff48-c929-11e7-8ae2-a347215ee796.png)

**Comment by cnobre** [comment]
![screen shot 2017-11-14 at 1 24 39 pm](https://user-images.githubusercontent.com/4120607/32802966-35616328-c93f-11e7-8fd1-1befc7310ed0.png)
