### ISSUE TITLE
Height-scaling of Family Selector and Tree

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#188]
Family Selector and Tree are not dynamically scaled to the available height: 

![image](https://user-images.githubusercontent.com/2039375/32797192-2a954efc-c92e-11e7-9db9-caee9e786702.png)
![image](https://user-images.githubusercontent.com/2039375/32797206-2ef84b48-c92e-11e7-9283-f95a0c0b627c.png)

**Comment by cnobre** [comment]
fixed with the wonders of sass (calc(100vh - xpx))
