### ISSUE TITLE
Layout issue in  50844627

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#191]
Why is there a child in the first place? 

![image](https://user-images.githubusercontent.com/2039375/32809814-9f51da68-c955-11e7-8e6b-e8a028deca14.png)

**Comment by cnobre** [comment]
![screen shot 2017-11-16 at 9 27 53 am](https://user-images.githubusercontent.com/4120607/32902762-81ff37ec-cab0-11e7-8072-8d4c17346204.png)

fixed!
