### ISSUE TITLE
Selection doesn't properly down-propagate in some cases 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#193]
See for example: 

![image](https://user-images.githubusercontent.com/2039375/32869713-b832a356-ca35-11e7-91ec-40dae711523a.png)

In Family 234.

**Comment by cnobre** [comment]
![screen shot 2017-11-16 at 9 04 14 am](https://user-images.githubusercontent.com/4120607/32901508-315fe5dc-caad-11e7-8ff6-3c0780125d70.png)
