### ISSUE TITLE
Family bar shown in cases where it shouldn't

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#196]
See: 

![image](https://user-images.githubusercontent.com/2039375/33029722-93beb074-cdd6-11e7-904d-43a534072f7e.png)

For POI, the bar shouldn't be there.

**Comment by alexsb** [comment]
This is a common problem also in our demo dataset: 

![image](https://user-images.githubusercontent.com/2039375/33243577-3005e708-d2a6-11e7-8fee-ae186d45f620.png)

**Comment by cnobre** [comment]
<img width="145" alt="screen shot 2017-11-27 at 10 55 49 pm" src="https://user-images.githubusercontent.com/4120607/33304470-45664f04-d3c6-11e7-96e3-3b0130d7894e.png">

Fixed
