### ISSUE TITLE
Other POIs break table layout

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#197]
See the following, with depression as POI: 

![image](https://user-images.githubusercontent.com/2039375/33030040-748b5aa8-cdd7-11e7-8a08-88fef5ff031b.png)

**Comment by cnobre** [comment]
<img width="1423" alt="screen shot 2017-11-26 at 11 15 44 am" src="https://user-images.githubusercontent.com/4120607/33243042-731d76a6-d29b-11e7-805a-d4aea3568a10.png">
