### ISSUE TITLE
Make slope lines consistent with row highlight

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#207]
![image](https://user-images.githubusercontent.com/2039375/33046787-d455d91c-ce0f-11e7-8fc4-89fa02c7fe78.png)

The orange slope line is much darker than the row highlight.

**Comment by cnobre** [comment]
this was actually deliberate.  It's a recent change. We had talked about getting rid of the semi-opaque nature of the slope lines.  The highlighted rows still have an opacity of less than 1. We can either change the opacity of the highlighted rows to 1, or just pick a lighter (yet still opaque) color for the slope lines to match the highlighted rows.

**Comment by cnobre** [comment]
remind here, is the issue that the color of the slope doesn't match up with the color of the highlighted row? Or that the slope line didn't start at the edge of the rect (with the number 1 inside it in the screenshot above)?

**Comment by alexsb** [comment]
It's the color
