### ISSUE TITLE
Resize POI Highlight when resizing column

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#208]
![image](https://user-images.githubusercontent.com/2039375/33110470-52012272-cf05-11e7-8b47-f931eaae4b48.png)

**Comment by cnobre** [comment]
![screen shot 2017-11-21 at 9 53 52 pm](https://user-images.githubusercontent.com/4120607/33110657-a073f104-cf06-11e7-8526-65d642b9a001.png)
