### ISSUE TITLE
change aggregation behavior on click and drag to show stippled node @ original location and only aggregate on release

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#21]
Right now, clicking and dragging on nodes moves their position and the associated edges. Instead, leave the edges in place, create a 'phantom' stippled node in it's place and only aggregate when the user releases the mouse.

**Comment by alexsb** [comment]
This is superseded by our alternative design decision to use the collapsed encodings (kid-grids, etc.) for also encoding aggregates.
