### ISSUE TITLE
Race is broken in anon dataset

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#211]
Only white appears. 

This is likely a problem with the json generation in @cnobre's python version, there are different capitalizations in the index.json.

**Comment by cnobre** [comment]
Race isn't broken. All the values in the race col for 'TenFamiliesAttrAnon.csv' are 'white'.

**Comment by alexsb** [comment]
Didn't we add a couple of non-white fields just to demonstrate this in march? If this isn't there anymore, should we do that again?

**Comment by cnobre** [comment]
We might have... but maybe those files got regenerated along the way? In any case, yes I can add some other races there no problem.

**Comment by alexsb** [comment]
ok, make sure to do it in a plausible way, i.e., for subfamilies and spouses, not for random people. At what point in our process should we do that?

**Comment by cnobre** [comment]
I'd say in the pre-processing.

**Comment by alexsb** [comment]
This was resolved a while ago.
