### ISSUE TITLE
Fix vertical sizing issue of family selector and tree

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#215]
See the whitespace at the bottom: 

![image](https://user-images.githubusercontent.com/2039375/33243847-78b8b4e0-d2aa-11e7-8d47-efa735b98e96.png)

Note that right now, adding multiple families to the selector changes the gap.

**Comment by cnobre** [comment]
The white space for the tree is static and I can reduce that to 0. The white space for the family selector changes as the size of the selected families table at the top grows. Have to think of a workaround.

**Comment by cnobre** [comment]
so is the issue here the difference in white space between the family selector and the tree? or the presence of any white space @ all?

**Comment by alexsb** [comment]
The presence of any whitespace.
