### ISSUE TITLE
Aggregation Rules

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#22]
If there is a primary attribute present in a given generation, all non-affected members of this generation are aggregated, but the generation is preserved through the affected individual node and the aggregate node for all non-affected. 

If there is no primary attribute present in a generation, it gets rolled up in to an aggregate in an older generation up to the level where the aggregation was triggered from.

**Comment by cnobre** [comment]
<img width="1024" alt="aggregation_example" src="https://cloud.githubusercontent.com/assets/4120607/22851565/5dc25fd8-efe3-11e6-86f2-d87af788c7f4.png">

<img width="768" alt="aggregation_hover" src="https://cloud.githubusercontent.com/assets/4120607/22851567/69afa490-efe3-11e6-843e-c614d396b71f.png">

**Comment by cnobre** [comment]
<img width="528" alt="nuclear_families" src="https://cloud.githubusercontent.com/assets/4120607/22865821/afe118e0-f128-11e6-8a04-d0796dbc7552.png">

Nuclear Families as defined for aggregation purposes. Nodes with two numbers belong to two nuclear families.

**Comment by alexsb** [comment]
This is partially solved, partially superseded.
