### ISSUE TITLE
Improve force-directed layout 

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#223]
make nodes smaller (potentially rectangles)
increase canvas size for this layout, even if it means pushing the table aside in this mode.

**Comment by alexsb** [comment]
Also the links are wonky, and this probably needs a little more space. 


![image](https://user-images.githubusercontent.com/2039375/36004884-25173e4c-0cf2-11e8-9df9-ddd3330cb769.png)

**Comment by cnobre** [comment]
This is clearly ART.
