### ISSUE TITLE
Add edges that are in a set

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#235]
Right now, it looks like only the edges from a set to a node are added: 

![image](https://user-images.githubusercontent.com/2039375/36005194-b710e8c4-0cf3-11e8-8ad3-caf1437ef8e1.png)

However, we need the edges that are in the set and that connect the nodes: 

![image](https://user-images.githubusercontent.com/2039375/36005208-c7f9e262-0cf3-11e8-95e8-35f617de4875.png)

**Comment by cnobre** [comment]
![screen shot 2018-02-11 at 4 12 43 pm](https://user-images.githubusercontent.com/4120607/36079975-75b6a080-0f46-11e8-9a39-9cdcc3028da8.png)
