### ISSUE TITLE
Sort table based on an attribute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#24]
We want to be able to sort the table based on any attribute by interacting with the table header. 

On sort, we'll add a slope chart between the tree and the table: 

![image](https://cloud.githubusercontent.com/assets/2039375/22849217/37de25a2-efb8-11e6-871a-2fe0d7e12438.png)

**Comment by anniecherk** [comment]
Mockup of sorting mechanism:
- Add a triangle up/ triangle down glyph below label, which alternates sort on click
- Click can occur anywhere in a reasonable amount of vertical space above column
- Only attributes with a numeric type can be sorted

![image](https://cloud.githubusercontent.com/assets/4534857/23108450/bf753f1e-f6ca-11e6-9ef6-22e8b312d3b9.png)

Issues:
- Is there a mechanism to "undo" a sort?
- Should there be an analogous categorical attribute clustering mechanism?

**Comment by alexsb** [comment]
Re Undo - there should be a "sort by tree" button somewhere on the tree. 

Re Categorical - yes, by clicking on a column all its elements should come to the top. That's another advantage of the categorical vis method we talked about in #10.

**Comment by cnobre** [comment]
Done. Slope Chart implementation is a separate issue.
