### ISSUE TITLE
Allow users to define baseline year for age calculations

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/lineage#27]
For some users, it might be important to be able to fix the date (e.g. if they are working on a data set that should not be changing (e.g. for screenshots or analyses), while other users will be ok with seeing the age relative to the current year.

We should allow users to view age relative to the current year (i.e. use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear) or to provide a baseline year. 

At a minimum, we should define a global variable for the baseline year.

**Comment by alexsb** [comment]
You mean to capture the date at which the dataset was collected? E.g., if we know that the data is current as of 2014, you would not consider someone born in 2000 to be 14, not 17 - (as it's 2017)?

**Comment by alexsb** [comment]
We're doing age-calculations now in pre-processing.
