### ISSUE TITLE
Deterministic Traversal / Sorting Strategy

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#282]
We want to have a user-chosen, deterministic traversal and sorting strategy. The main problem right now is the decisions of which leaf to visit first. 

As far as I know, this is alphabetical right now; I'm not sure what effect the sorting has. We need to do this based on data; alphabetical is one option, but we want many others. 

Ones that work independent on type: 

 * Alphabetical 
 * By Degree
 * By Pagerank
 * By Type (alphabetical)
 
If it's based on the attributes of a type, I'd suggest to put the items of the sorted type first, sort them, and then follow by all other types.

**Comment by alexsb** [comment]
For now, sort children alphabetically in extract tree.

**Comment by cnobre** [comment]
done.
