### ISSUE TITLE
Sort attributes alphabetically

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineage#284]
![image](https://user-images.githubusercontent.com/4129755/37775833-458a7d16-2de4-11e8-8967-2f632713914f.png)

**Comment by cnobre** [comment]
![screen shot 2018-03-24 at 7 53 35 pm](https://user-images.githubusercontent.com/4120607/37870850-0ddd9686-2f9d-11e8-885c-f30992d25b7c.png)


Done.
