### ISSUE TITLE
Separate Level and Tree mode from Aggregation

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#286]
Right now we have the following behavior: 

Tree layout is always unaggregated
Level layout starts aggregated but can be unaggregated

We should separate that out with dedicated menu options.

Aggregation / not-aggregated in level mode stays the same, i.e., it applies recusively. 

Aggregation in tree mode is added, lower levels of aggregated nodes are not shown. 

This has some important implications for partial aggregation, which we do want to support.

**Comment by cnobre** [comment]
done
