### ISSUE TITLE
Sometimes, coloring is off in adjacency matrix

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#288]
In level mode, for the row corresponding to the incoming edge, the adjacency matrix is incorrectly lighter: 
![image](https://user-images.githubusercontent.com/2039375/37803810-9be7477c-2df6-11e8-9339-7ac67e93e2ff.png)

it detects two ‘nodes’ (that incoming edge ends in a ‘level mode’ node). And since only one of those two nodes have that edge, it’s opacity is only 50%

**Comment by cnobre** [comment]
![screen shot 2018-03-22 at 6 12 28 pm](https://user-images.githubusercontent.com/4120607/37804944-acb85d24-2dfc-11e8-89fe-4e49f6a1e84e.png)

fixed.
