### ISSUE TITLE
Use different colors for multiple edges / heat map and single edge in adjacency matrix. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#289]
We should use different colors for cases where a row represents an aggregate, and where it represents a single node: 

![image](https://user-images.githubusercontent.com/2039375/37803881-033c778a-2df7-11e8-87e5-23f494b4bc5a.png)

We actually do that already for the hidden edge matrix.

**Comment by cnobre** [comment]
are we still doing this or are we only using different colors for different types?

**Comment by alexsb** [comment]
good question, these are in conflict. maybe have a slight background color for the type, gray cells for single edges, and another color for aggregates?

**Comment by cnobre** [comment]
will try it out.

**Comment by cnobre** [comment]
check.
