### ISSUE TITLE
Make lables in nodes definable

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#29]
I don't think the current implementation with age is necessarily always helpful. 

We could think about what we can put in there - maybe something related to primary (#18) or secondary (#19) attribute.

**Comment by cnobre** [comment]
I agree. It was a placeholder to indicate we can label the nodes with any attribute. Let's pick something more relevant for the Monday meeting.

**Comment by alexsb** [comment]
I think we'll skip labels in the nodes.
