### ISSUE TITLE
SVG sizing

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#296]
Some problematic cases: 

![image](https://user-images.githubusercontent.com/2039375/37851142-6531b73c-2ea3-11e8-9e87-4b29de337caf.png)

![image](https://user-images.githubusercontent.com/2039375/37851165-7ae2998e-2ea3-11e8-897c-7dc4910af0d3.png)

When I scroll to the bottom on the tree side, the table and tree aren't properly synced: 

![image](https://user-images.githubusercontent.com/2039375/37851219-aca25cde-2ea3-11e8-8b76-4356c42b7d80.png)

**Comment by cnobre** [comment]
fixed!
