### ISSUE TITLE
Center text in labels

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#30]
![image](https://cloud.githubusercontent.com/assets/2039375/22851220/58095a66-efd8-11e6-896e-9f507dfbc071.png)

Not quite in center vertically.

**Comment by cnobre** [comment]
<img width="313" alt="screen shot 2017-02-10 at 11 53 11 pm" src="https://cloud.githubusercontent.com/assets/4120607/22851862/2282abd6-efec-11e6-98a3-0e2acea7e73f.png">
