### ISSUE TITLE
Don't show hidden edges for unambiguous level mode

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#300]
Here, the first edge shouldn't be here, but the second should: 

![image](https://user-images.githubusercontent.com/2039375/37852265-950eeae8-2ea7-11e8-9b31-70f8f69c4b55.png)

In practice, this has significant implication in un-aggregated mode. Most of these edges shouldn't be here: 

![image](https://user-images.githubusercontent.com/2039375/37852288-a8f15be0-2ea7-11e8-97e1-107bff931b76.png)

**Comment by cnobre** [comment]
![screen shot 2018-03-24 at 7 20 38 pm](https://user-images.githubusercontent.com/4120607/37870647-7bcdec68-2f98-11e8-9280-09145111a691.png)

fixed!
