### ISSUE TITLE
Replace stippled edges with solid lines

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#304]
Because rendering multiple stippled edges on top of each other leads to some appear full, some stippled: 

![image](https://user-images.githubusercontent.com/2039375/37870671-1b98e2c0-2f99-11e8-9d41-77a01d90fa3a.png)

**Comment by cnobre** [comment]
![screen shot 2018-03-24 at 7 28 49 pm](https://user-images.githubusercontent.com/4120607/37870720-9caf5236-2f99-11e8-9ae1-5f42a50708ea.png)

check.

**Comment by alexsb** [comment]
Well, that's only a partial fix. Right now, the same thing happens with alpha. Do alpha = 1.

**Comment by cnobre** [comment]
done.
