### ISSUE TITLE
Enable switching between families. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#32]
Like in UpSet, we should be able to switch between different datasets through the user interface. 

While we will hopefully have a couple of interesting pedigrees, it's also useful to load dedicated test-datasets.

**Comment by alexsb** [comment]
Revising this: we want to be able to switch between different families which are all in the same dataset. In addition, we want a small view that lists the families and important attributes about them, such as the number of nodes and the number of "cases".

**Comment by ngehlenborg** [comment]
Should this be part of the attribute browser? It might be appropriate to place the family selection at the top in a separate section.

**Comment by alexsb** [comment]
Yes, spatially that's the plan. I think it should be it's own view/class though.

**Comment by cnobre** [comment]
Done!
