### ISSUE TITLE
Preserve selected rows on scroll. 

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#35]
### Observed behavior
*In order to preserve selected rows on scroll, clicking on a row modifies the data bound to the element to 'selected' = true. The problem with this is that when the user clicks on a new row (not in multi-selection mode/cmd key) that doesn't modify the data of the previously selected row(s). 

### Expected behavior
* When user clicks on a row without cmd, it should clear all other selected rows (including the ones outside of the viewport)

**Comment by alexsb** [comment]
This is solved, probably as a side-effect of how the tree is now drawn/clipped.
