### ISSUE TITLE
Allow user to select primary and secondary attributes through the attributes panel

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#36]
The primary attribute is moved to a special spot at the top. The secondary attribute is moved to to a special spot right below it. 

In a first iteration, we just pick one category to be the primary.

**Comment by aaljuhani** [comment]
I noticed that when we have long list of attribute dragging an attribute to the top of the list is kind of difficult. An alternative way is to allow the user to click on a label that is shown when hovering over the attribute as shown  

<img width="1024" alt="sketches - 21" src="https://cloud.githubusercontent.com/assets/3948548/23141727/71872b36-f775-11e6-854b-ff0913512bd3.png">

@(alexsb) any preference?

**Comment by alexsb** [comment]
Yes, good point. Drag and drop is nice for re-ordering, but for selecting primary attributes a button might be better.
