### ISSUE TITLE
Kids are placed in the wrong y position in multi-spouse families. 

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#42]
### Observed behavior
* The affected male kid in this example is the child of the mom with the affected dad. So he should be placed next to the other two male siblings (lower y than the unaffected dad) 

![screen shot 2017-02-18 at 11 35 57 am](https://cloud.githubusercontent.com/assets/4120607/23095902/391bd1f4-f5cf-11e6-87b7-08e6df9d2da4.png)

**Comment by alexsb** [comment]
I think this has been solved.
