### ISSUE TITLE
when hidding nodes: how to deal with branches that end with no affected children.

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#43]
This doesn't happen in our current suicide dataset but if you change the 'selected' attribute, that can (and will) happen. 

Have to think about how to handle this.

**Comment by alexsb** [comment]
Two solutions: 

 1. leave an empty row 
 2. show an aggregate

I tend to favor option 1, but might change my mind when seeing a real example.

**Comment by cnobre** [comment]
Opted for leaving an empty row. Addressed this in a previous commit.
