### ISSUE TITLE
Select category or feature range to drive the primary attribute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#46]
As the primary attribute determines the layout of the graph, we need to be able to define what is "in" and what is "out". 

For Categorical data, we want to select 1-n categories to make up the primary attribute. 

For Numerical data, we want to be able to brush a region.

![screen shot 2017-02-15 at 12 01 27 pm](https://cloud.githubusercontent.com/assets/4120607/22990459/83a5b88a-f376-11e6-82d8-bdf15db307fc.png)

**Comment by cnobre** [comment]
Done! Alpha is behind us!
