### ISSUE TITLE
Resize Table Columns by Dragging

### ISSUE THREAD

**Issue by anniecherk** [Caleydo/lineage#49]
Should be able to dynamically resize the column widths, ie by clicking and dragging.

Two possible behaviors:
1) This shrinks all the other column widths ("widening the column")
2) This shrinks the column widths of the neighbor on the side that's being dragged ("moving the boundary")

Option 2 is the behavior in, ie Google Sheets, so that might make more sense and is easier to implement...

- Would also be nice to have a reset mechanism- ie, double clicking the column.
- Might be good to have a minimum column size (say N pixels), so that you cannot squash columns down smaller than N pixels. (If you want a column smaller than N pixels you should probably delete it)

**Comment by cnobre** [comment]
Done.
