### ISSUE TITLE
missing life line (or extremely short life line?)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/lineage#50]
* Release number or git hash: b2cc6ce2ba4c70c3edf0c3f6da396cfd2bed6c49
* Web browser version and OS: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
* Environment (local or deployed): local (`npm start`)

### Steps to reproduce

1. Launch app.
2. Scroll genealogy down to nodes with id "17"

### Observed behavior
* One individual doesn't seem to have life line.

![image](https://cloud.githubusercontent.com/assets/1216518/23131726/25085558-f759-11e6-82c5-642ce962b8be.png)

### Expected behavior
* A life line or other indicator why the individual doesn't have one.

**Comment by cnobre** [comment]
Oh he does, it's just REALLY short. If you zoom in, you can see the tip of the age label and end of Life marker showing up. I think that was a 2year old case. :( 

![screen shot 2017-02-20 at 10 57 17 am](https://cloud.githubusercontent.com/assets/4120607/23136753/5f3468b4-f75b-11e6-8b7d-4647cca2f21f.png)

**Comment by ngehlenborg** [comment]
Ok, thanks for the clarification. Just a suggestion: would it make sense to place the rightmost edge of the nodes on the birthdate so that these things don't get hidden behind the node? Not sure what the consequences are, but since there shouldn't be any events for an individual to the left of (i.e. before) the birthdate, this might be a sensible enhancement.
