### ISSUE TITLE
Edges are drawn on top of nodes when genealogy is redrawn

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/lineage#51]
* Release number or git hash: b2cc6ce2ba4c70c3edf0c3f6da396cfd2bed6c49
* Web browser version and OS: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
* Environment (local or deployed): local (`npm start`)

### Steps to reproduce

1. Scroll the genealogy all the way to the bottom 
2. Start scrolling back up to force re-rendering of the genealogy.

### Observed behavior
* Edges are drawn on top of nodes.

![feb-20-2017 10-43-17](https://cloud.githubusercontent.com/assets/1216518/23131894/c97d4f44-f759-11e6-9f47-65a6bbddd04a.gif)

### Expected behavior
* Edges are drawn behind nodes.

**Comment by cnobre** [comment]
What tool do you use to record these gif screenshots? Quicktime? Very cool to show behavior.

**Comment by ngehlenborg** [comment]
GIPHY
