### ISSUE TITLE
Hidden nodes should be highlightable

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#53]
Extracting this out of #44: Hidden nodes should be highlightable, but not using the line highlight, but by highlighting a frame.

We want to be able to select those people.

**Comment by cnobre** [comment]
How would one differentiate between the user behavior to highlight the right most node or a hidden node? Right now, mousing over a row selects the right most node.

**Comment by alexsb** [comment]
That's fine. But mousing over a specific node should highlight that specific node.

**Comment by cnobre** [comment]
Ah, you mean a frame around the node (that is, change the stroke of the node). That makes sense.

**Comment by alexsb** [comment]
Yes. And I would also add that frame to the righ-most node, just to be consistent.

**Comment by cnobre** [comment]
summarizing: 
1) mouse over a row (anywhere) highlights the area of the row to the right of the  affected node at the far right. 
2) mouse over a hidden node, changes the stroke of that node to red or something. 
3) did your last comment imply that mousing over a hidden node ALSO outlines the stroke of the affected node in that row?

**Comment by alexsb** [comment]
1. mouse over a row RIGHT OF the rightmost node highlights the row and the rightmost node 
2. mouse over ANY node highlights the frame of the node using the same orange highlight color as always
3. mouse over the rightmost node ALSO highlights the row.

**Comment by cnobre** [comment]
Crystal Clear. 👍
