### ISSUE TITLE
Primary and Secondary Attribute selection in panel should be separated from the list of all attributes

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#54]
I think that the area that shows what the primary and secondary attributes are should be above and separate from the list of Data Attributes. 

### Observed behavior
Right now, when you select two attributes and move them to the top, they then seem to just be part of the list and there's no indication that they are the primary and secondary attributes. 

### Expected behavior
* I think we have to make it clear -> this is the primary, this is the secondary. 

So I would have exactly what you have but keep the "Data Selection" list below, and create a new header "primary attribute" and another 'secondary attribute' above it where the user drags attributes from the list onto.

**Comment by alexsb** [comment]
We decided against this - primary and secondary are highlighted with a flag, but not moved.
