### ISSUE TITLE
Deal with hiding Multi Parent Families 

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#60]
Consider how to show multi parent families. 

Options include: 

1) Duplicate parent nodes so that each 'subFamily' is it's own entitiy. 
2)Create a single family entity with all involved parents stacked at the top. 

![multiparent](https://cloud.githubusercontent.com/assets/4120607/23191918/a0449592-f85d-11e6-915a-558983af79e1.png)

**Comment by alexsb** [comment]
This isn't a bug but a restriction of our approach. We should definitely think about how to handle multi-parent families, but that might be a separate paper.

**Comment by cnobre** [comment]
done!
