### ISSUE TITLE
Table: on hover: tooltip & individual highlighting

### ISSUE THREAD

**Issue by anniecherk** [Caleydo/lineage#64]
## Tooltip info:

![githubissues_3](https://cloud.githubusercontent.com/assets/4534857/23229373/49c84d58-f8fd-11e6-89b2-22c0244d9f31.jpg)

### Categorical
- [ ] Column Summaries: show #/bar
- [ ] Data: Show #/container

### Quantitative
- [ ] Column Summaries: show #/bin
- [ ] Data: Show value

### ID
- [ ] Data: Show list of ID's in container

## Highlight the individual across the columns:
![githubissues_4](https://cloud.githubusercontent.com/assets/4534857/23229562/f65fe38c-f8fd-11e6-8700-82e2f44f9d0d.jpg)

**Comment by alexsb** [comment]
This is largely implemented. Will open up new issues for details when necessary.
