### ISSUE TITLE
Incorrect line destination for couples

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#69]
See: 
![image](https://cloud.githubusercontent.com/assets/2039375/23387230/98cb07be-fd18-11e6-982d-01af45c1f0d8.png)

**Comment by cnobre** [comment]
![screen shot 2017-03-01 at 10 10 29 am](https://cloud.githubusercontent.com/assets/4120607/23471669/5364f842-fe67-11e6-9ad4-cafd1c6d0c06.png)

**Comment by alexsb** [comment]
So the position of the node was wrong. Great that it works!

**Comment by cnobre** [comment]
Yeah, that was an easy fix :)
