### ISSUE TITLE
Time axis extends into the future?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/lineage#79]
It seems that the time axis extends beyond the current date or the age lines are too short:

![image](https://cloud.githubusercontent.com/assets/1216518/23591619/fae296c2-01c0-11e7-81d6-ec6de3b55519.png)

**Comment by ngehlenborg** [comment]
Related to this: how important is it to distinguish between "current date" and "data collection date"? Once that distance between the two starts growing, the visualization could become misleading by indicating that people are still alive who might have committed suicide or passed away for other reasons in the mean time. 

Indicators (e.g. vertical lines such as the one shown above but prettier) for "current date" and "data collection date" could be used to convey increasing uncertainty (the further the lines are apart, the more uncertain the data has become).

**Comment by alexsb** [comment]
The issue discussed in @ngehlenborg's comment is covered in #27. The original issue is valid.

**Comment by ngehlenborg** [comment]
Thanks for the reminder about #27. I'd say the issues are related but not quite the same.

**Comment by alexsb** [comment]
This still occurs:
![image](https://cloud.githubusercontent.com/assets/2039375/24078026/1965c7bc-0c26-11e7-9001-61c7b3fa7f01.png)
