### ISSUE TITLE
table needs to re-render on family selection

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#82]
The table currently doesn't update when a family is selected. So the size of the table and the graph and the table are not the same, leading to the offset seen in the screenshot below. 

![screen shot 2017-03-08 at 12 34 54 pm](https://cloud.githubusercontent.com/assets/4120607/23720370/c83be65a-03fb-11e7-9754-83babe44519d.png)

**Comment by alexsb** [comment]
Fixed
